### ISSUE TITLE
Is there any specific reason for the version constraint?

### ISSUE THREAD

**Issue by cmpute** [bab2min/EigenRand#22]
I tried to compile my code against Eigen 3.3.4 (bundled in Ubuntu 18.04) and manually relieved the version constraint. The compilation is successful, although I haven't tested the output. So I'm curious is there any specific reason for constraint Eigen > 3.3.7? It will be convenient if I don't need to override system Eigen.

**Comment by bab2min** [comment]
Hello @cmpute 
The reason is that the version 3.3.7 seems to be widely used, so I only tested it with version 3.3.7 or higher.
Actually, it is easy to test older versions. I'll add tests for old versions to workflows.

**Comment by cmpute** [comment]
Thanks for the clarification!

**Comment by bab2min** [comment]
A compilation error with Eigen 3.3.4 and -mavx option is patched.
A new version will be published soon! Thank you :)
