### ISSUE TITLE
Large (scale) samples with MvNormalGen

### ISSUE THREAD

**Issue by izsahara** [bab2min/EigenRand#30]
Hi, apologies in advance as this may look long winded but to reproduce the issue simply just copy-paste the following piece of code
```
#include <Eigen/Dense>
#include <EigenRand/EigenRand>

typedef Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic, Eigen::ColMajor> TMatrix;
typedef Eigen::VectorXd TVector;
using Eigen::Rand::Vmt19937_64;
Vmt19937_64 gen_eigen;

void cdist(const TMatrix& X1, const TMatrix& X2, TMatrix& D, bool squared = false) {
    // |X1(i) - X2(j)^T|^2 = |X1(i)|^2 + |X2(j)|^2 - (2 * X1(i)^T X2(j))
    D = ((-2.0 * (X1 * X2.transpose())).colwise()
        + X1.rowwise().squaredNorm()).rowwise()
        + X2.rowwise().squaredNorm().transpose();
    if (!squared) { D = (D.array().sqrt()).matrix(); }
}

const TMatrix Matern52(const TMatrix& X1, const TMatrix& X2, TVector& length_scale) {
    TMatrix R(X1.rows(), X2.rows());
    const TMatrix X1sc = X1.array().rowwise() / length_scale.transpose().array();
    const TMatrix X2sc = X2.array().rowwise() / length_scale.transpose().array();
    cdist(X1sc, X2sc, R, false);
    R *= sqrt(5);
    return ((1 + R.array() + square(R.array()) / 3) * (exp(-R.array()))).matrix();
}

void xiong1d(const Eigen::Ref<const TMatrix>& X, Eigen::Ref<TMatrix> Y) {
    Y = -0.5 * (sin((40 * pow((X.array() - 0.85), 4)).array()) * cos((2.5 * (X.array() - 0.95)).array()) + 0.5 * (X.array() - 0.9) + 1);
}

TMatrix sample_mvn(const TVector& mean, const TMatrix& K) {
    MvNormalGen sampler = makeMvNormalGen(mean, K);
    return sampler.generate(gen_eigen);
}

void test_mvn_sample() {
    TVector x_range = TVector::LinSpaced(10, 0, 1);
    TMatrix X = Eigen::Map<TVector>(x_range.data(), 10);
    TMatrix Y(X.rows(), 1);
    xiong1d(X, Y);
    TVector length_scale = TVector::Ones(1);
    TMatrix K = Matern52(X, X, length_scale);
    std::cout << "K =\n" << K << std::endl;
    TVector mean = TVector::Zero(X.rows());
    TMatrix mvn_samples = sample_mvn(mean, K);
    std::cout << "MVN_SAMPLE =\n" << mvn_samples << std::endl;
}

int main() {
   test_mvn_sample();
   return 0;
}
```
This should give out 
```
K =
       1 0.989851 0.960808 0.916168 0.859902 0.795934 0.727763 0.658294 0.589808 0.523994
0.989851        1 0.989851 0.960808 0.916168 0.859902 0.795934 0.727763 0.658294 0.589808
0.960808 0.989851        1 0.989851 0.960808 0.916168 0.859902 0.795934 0.727763 0.658294
0.916168 0.960808 0.989851        1 0.989851 0.960808 0.916168 0.859902 0.795934 0.727763
0.859902 0.916168 0.960808 0.989851        1 0.989851 0.960808 0.916168 0.859902 0.795934
0.795934 0.859902 0.916168 0.960808 0.989851        1 0.989851 0.960808 0.916168 0.859902
0.727763 0.795934 0.859902 0.916168 0.960808 0.989851        1 0.989851 0.960808 0.916168
0.658294 0.727763 0.795934 0.859902 0.916168 0.960808 0.989851        1 0.989851 0.960808
0.589808 0.658294 0.727763 0.795934 0.859902 0.916168 0.960808 0.989851        1 0.989851
0.523994 0.589808 0.658294 0.727763 0.795934 0.859902 0.916168 0.960808 0.989851        1

MVN_SAMPLE =
-8.07388
-7.99194
-7.75746
-7.41463
-6.69153
 -5.8611
-5.10573
-4.42873
-3.50118
-2.69687
```

As you can see the MVN samples look out of range, reproducing this issue (**same `mean` and `K` value**) in python with `numpy.random.default_rng().multivariate_normal(mean=mean, cov=K, check_valid='ignore')` would **(consistently)** give me a max MVN range of around (-2, 2)

**Comment by bab2min** [comment]
Hello @izsahara,
Thank you for sharing reproducible code. I'll test it asap.

**Comment by bab2min** [comment]
I've built a test binary for Windows 10 64bit : [test.zip](https://github.com/bab2min/EigenRand/files/7210563/test.zip)
Could you run it and share the result?

In my system (Windows 10 edu 64bit, AMD Ryzen 7 3700X), it yields following results:
```text
Running main() from c:\a\1\s\thirdparty\googletest\googletest\src\gtest_main.cc
[==========] Running 40 tests from 4 test cases.
[----------] Global test environment set-up.
[----------] 2 tests from Issue
[ RUN      ] Issue.30
K =
       1 0.989851 0.960808 0.916168 0.859902 0.795934 0.727763 0.658294 0.589808 0.523994
0.989851        1 0.989851 0.960808 0.916168 0.859902 0.795934 0.727763 0.658294 0.589808
0.960808 0.989851        1 0.989851 0.960808 0.916168 0.859902 0.795934 0.727763 0.658294
0.916168 0.960808 0.989851        1 0.989851 0.960808 0.916168 0.859902 0.795934 0.727763
0.859902 0.916168 0.960808 0.989851        1 0.989851 0.960808 0.916168 0.859902 0.795934
0.795934 0.859902 0.916168 0.960808 0.989851        1 0.989851 0.960808 0.916168 0.859902
0.727763 0.795934 0.859902 0.916168 0.960808 0.989851        1 0.989851 0.960808 0.916168
0.658294 0.727763 0.795934 0.859902 0.916168 0.960808 0.989851        1 0.989851 0.960808
0.589808 0.658294 0.727763 0.795934 0.859902 0.916168 0.960808 0.989851        1 0.989851
0.523994 0.589808 0.658294 0.727763 0.795934 0.859902 0.916168 0.960808 0.989851        1
MVN_SAMPLE =
-0.0695708
  0.110541
   0.25448
  0.357316
   0.40815
  0.308747
 0.0779976
  -0.15896
 -0.350616
 -0.478576
[       OK ] Issue.30 (49 ms)
...
```

**Comment by izsahara** [comment]
Hi, thanks for the quick response 

```
Running main() from c:\a\1\s\thirdparty\googletest\googletest\src\gtest_main.cc
[==========] Running 40 tests from 4 test cases.
[----------] Global test environment set-up.
[----------] 2 tests from Issue
[ RUN      ] Issue.30
K =
       1 0.989851 0.960808 0.916168 0.859902 0.795934 0.727763 0.658294 0.589808 0.523994
0.989851        1 0.989851 0.960808 0.916168 0.859902 0.795934 0.727763 0.658294 0.589808
0.960808 0.989851        1 0.989851 0.960808 0.916168 0.859902 0.795934 0.727763 0.658294
0.916168 0.960808 0.989851        1 0.989851 0.960808 0.916168 0.859902 0.795934 0.727763
0.859902 0.916168 0.960808 0.989851        1 0.989851 0.960808 0.916168 0.859902 0.795934
0.795934 0.859902 0.916168 0.960808 0.989851        1 0.989851 0.960808 0.916168 0.859902
0.727763 0.795934 0.859902 0.916168 0.960808 0.989851        1 0.989851 0.960808 0.916168
0.658294 0.727763 0.795934 0.859902 0.916168 0.960808 0.989851        1 0.989851 0.960808
0.589808 0.658294 0.727763 0.795934 0.859902 0.916168 0.960808 0.989851        1 0.989851
0.523994 0.589808 0.658294 0.727763 0.795934 0.859902 0.916168 0.960808 0.989851        1
MVN_SAMPLE =
-0.0695708
  0.110541
   0.25448
  0.357316
   0.40815
  0.308747
 0.0779976
  -0.15896
 -0.350616
 -0.478576
```

This is what I got from running `test.exe`

**Comment by bab2min** [comment]
@izsahara 
Thank you for sharing your result. It seems not to be hardware issue fortunately.

For questions related to declaring `gen_eigen`, I think it's okay. In that situation every source file has its own `gen_eigen`. The only situation that can be problematic is when `gen_eigen` declared as a global variable and it is used concurrently by multiple threads. 

Could you try below code with the recent EigenRand : https://github.com/bab2min/EigenRand/releases/tag/v0.3.6d
```cpp
#include <Eigen/Dense>
#include <EigenRand/EigenRand>

using TMatrix = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic, Eigen::ColMajor>;
using TVector = Eigen::VectorXd;
Eigen::Rand::P8_mt19937_64 gen_eigen{ 42 };

void cdist(const TMatrix& X1, const TMatrix& X2, TMatrix& D, bool squared = false) 
{
    // |X1(i) - X2(j)^T|^2 = |X1(i)|^2 + |X2(j)|^2 - (2 * X1(i)^T X2(j))
    D = ((-2.0 * (X1 * X2.transpose())).colwise()
        + X1.rowwise().squaredNorm()).rowwise()
        + X2.rowwise().squaredNorm().transpose();
    if (!squared) { D = (D.array().sqrt()).matrix(); }
}

const TMatrix Matern52(const TMatrix& X1, const TMatrix& X2, TVector& length_scale) 
{
    TMatrix R(X1.rows(), X2.rows());
    const TMatrix X1sc = X1.array().rowwise() / length_scale.transpose().array();
    const TMatrix X2sc = X2.array().rowwise() / length_scale.transpose().array();
    cdist(X1sc, X2sc, R, false);
    R *= sqrt(5);
    return ((1 + R.array() + square(R.array()) / 3) * (exp(-R.array()))).matrix();
}

void xiong1d(const Eigen::Ref<const TMatrix>& X, Eigen::Ref<TMatrix> Y) 
{
    Y = -0.5 * (sin((40 * pow((X.array() - 0.85), 4)).array()) * cos((2.5 * (X.array() - 0.95)).array()) + 0.5 * (X.array() - 0.9) + 1);
}

TMatrix sample_mvn(const TVector& mean, const TMatrix& K) 
{
    auto sampler = Eigen::Rand::makeMvNormalGen(mean, K);
    return sampler.generate(gen_eigen);
}

int main()
{
    std::cout << "SIMD arch: " << Eigen::SimdInstructionSetsInUse() << std::endl;

    TVector x_range = TVector::LinSpaced(10, 0, 1);
    TMatrix X = Eigen::Map<TVector>(x_range.data(), 10);
    TMatrix Y(X.rows(), 1);
    xiong1d(X, Y);
    TVector length_scale = TVector::Ones(1);
    TMatrix K = Matern52(X, X, length_scale);
    std::cout << "K =\n" << K << std::endl;
    TVector mean = TVector::Zero(X.rows());
    TMatrix mvn_samples = sample_mvn(mean, K);
    std::cout << "MVN_SAMPLE =\n" << mvn_samples << std::endl;

    return 0;
}
```
If the problem is caused by differences in compilation environment, this code will yield different results from the above one.

**Comment by izsahara** [comment]
This is the output (Release x64) using v0.3.6d, The results are different (On Debug x64 build results are also different),

```
SIMD arch: SSE, SSE2
K =
       1 0.989851 0.960808 0.916168 0.859902 0.795934 0.727763 0.658294 0.589808 0.523994
0.989851        1 0.989851 0.960808 0.916168 0.859902 0.795934 0.727763 0.658294 0.589808
0.960808 0.989851        1 0.989851 0.960808 0.916168 0.859902 0.795934 0.727763 0.658294
0.916168 0.960808 0.989851        1 0.989851 0.960808 0.916168 0.859902 0.795934 0.727763
0.859902 0.916168 0.960808 0.989851        1 0.989851 0.960808 0.916168 0.859902 0.795934
0.795934 0.859902 0.916168 0.960808 0.989851        1 0.989851 0.960808 0.916168 0.859902
0.727763 0.795934 0.859902 0.916168 0.960808 0.989851        1 0.989851 0.960808 0.916168
0.658294 0.727763 0.795934 0.859902 0.916168 0.960808 0.989851        1 0.989851 0.960808
0.589808 0.658294 0.727763 0.795934 0.859902 0.916168 0.960808 0.989851        1 0.989851
0.523994 0.589808 0.658294 0.727763 0.795934 0.859902 0.916168 0.960808 0.989851        1
MVN_SAMPLE =
  13.88
13.7391
 13.336
12.7324
11.8368
10.7217
9.52384
8.32982
6.70797
4.78306
```

**Comment by bab2min** [comment]
Umm, it seems that the option to use AVX2 is missing at the compiling. But it doesn't seem to bring a difference in the results.
The compile options are assumed to be the same as before(https://github.com/bab2min/EigenRand/issues/29#issuecomment-913089644), right?
I think I need to analyze the compiled binary. 
Could you share your Debug x64 .exe file here? 

And also you can try another piece of code:
```cpp
#include <Eigen/Dense>
#include <EigenRand/EigenRand>
#include <random>

using TMatrix = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic, Eigen::ColMajor>;
using TVector = Eigen::VectorXd;
std::mt19937_64 gen_eigen{ 42 };

void cdist(const TMatrix& X1, const TMatrix& X2, TMatrix& D, bool squared = false) 
{
    // |X1(i) - X2(j)^T|^2 = |X1(i)|^2 + |X2(j)|^2 - (2 * X1(i)^T X2(j))
    D = ((-2.0 * (X1 * X2.transpose())).colwise()
        + X1.rowwise().squaredNorm()).rowwise()
        + X2.rowwise().squaredNorm().transpose();
    if (!squared) { D = (D.array().sqrt()).matrix(); }
}

const TMatrix Matern52(const TMatrix& X1, const TMatrix& X2, TVector& length_scale) 
{
    TMatrix R(X1.rows(), X2.rows());
    const TMatrix X1sc = X1.array().rowwise() / length_scale.transpose().array();
    const TMatrix X2sc = X2.array().rowwise() / length_scale.transpose().array();
    cdist(X1sc, X2sc, R, false);
    R *= sqrt(5);
    return ((1 + R.array() + square(R.array()) / 3) * (exp(-R.array()))).matrix();
}

void xiong1d(const Eigen::Ref<const TMatrix>& X, Eigen::Ref<TMatrix> Y) 
{
    Y = -0.5 * (sin((40 * pow((X.array() - 0.85), 4)).array()) * cos((2.5 * (X.array() - 0.95)).array()) + 0.5 * (X.array() - 0.9) + 1);
}

TMatrix sample_mvn(const TVector& mean, const TMatrix& K) 
{
    auto sampler = Eigen::Rand::makeMvNormalGen(mean, K);
    return sampler.generate(gen_eigen);
}

int main()
{
    std::cout << "SIMD arch: " << Eigen::SimdInstructionSetsInUse() << std::endl;

    TVector x_range = TVector::LinSpaced(10, 0, 1);
    TMatrix X = Eigen::Map<TVector>(x_range.data(), 10);
    TMatrix Y(X.rows(), 1);
    xiong1d(X, Y);
    TVector length_scale = TVector::Ones(1);
    TMatrix K = Matern52(X, X, length_scale);
    std::cout << "K =\n" << K << std::endl;
    TVector mean = TVector::Zero(X.rows());
    TMatrix mvn_samples = sample_mvn(mean, K);
    std::cout << "MVN_SAMPLE =\n" << mvn_samples << std::endl;
    return 0;
}
```
It just replaces the random number generator with the c++ standard. I think the packet random number generator is suspicious. If the above code works well, it becomes clear that the problem is with the packet random number generator.

**Comment by izsahara** [comment]
> 
> 
> This is the output (Release x64) using v0.3.6d, The results are different (On Debug x64 build results are also different),
> 
> ```
> SIMD arch: SSE, SSE2
> K =
>        1 0.989851 0.960808 0.916168 0.859902 0.795934 0.727763 0.658294 0.589808 0.523994
> 0.989851        1 0.989851 0.960808 0.916168 0.859902 0.795934 0.727763 0.658294 0.589808
> 0.960808 0.989851        1 0.989851 0.960808 0.916168 0.859902 0.795934 0.727763 0.658294
> 0.916168 0.960808 0.989851        1 0.989851 0.960808 0.916168 0.859902 0.795934 0.727763
> 0.859902 0.916168 0.960808 0.989851        1 0.989851 0.960808 0.916168 0.859902 0.795934
> 0.795934 0.859902 0.916168 0.960808 0.989851        1 0.989851 0.960808 0.916168 0.859902
> 0.727763 0.795934 0.859902 0.916168 0.960808 0.989851        1 0.989851 0.960808 0.916168
> 0.658294 0.727763 0.795934 0.859902 0.916168 0.960808 0.989851        1 0.989851 0.960808
> 0.589808 0.658294 0.727763 0.795934 0.859902 0.916168 0.960808 0.989851        1 0.989851
> 0.523994 0.589808 0.658294 0.727763 0.795934 0.859902 0.916168 0.960808 0.989851        1
> MVN_SAMPLE =
>   13.88
> 13.7391
>  13.336
> 12.7324
> 11.8368
> 10.7217
> 9.52384
> 8.32982
> 6.70797
> 4.78306
> ```
(For Comment Above) : [debug64_1.zip](https://github.com/bab2min/EigenRand/files/7229122/debug64_1.zip)




> 
> 
> Umm, it seems that the option to use AVX2 is missing at the compiling. But it doesn't seem to bring a difference in the results.
> The compile options are assumed to be the same as before([#29 (comment)](https://github.com/bab2min/EigenRand/issues/29#issuecomment-913089644)), right?
> I think I need to analyze the compiled binary.
> **Could you share your Debug x64 .exe file here?**
> 
> And also you can try another piece of code:
> 
> ```c++
> #include <Eigen/Dense>
> #include <EigenRand/EigenRand>
> #include <random>
> 
> using TMatrix = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic, Eigen::ColMajor>;
> using TVector = Eigen::VectorXd;
> std::mt19937_64 gen_eigen{ 42 };
> 
> void cdist(const TMatrix& X1, const TMatrix& X2, TMatrix& D, bool squared = false) 
> {
>     // |X1(i) - X2(j)^T|^2 = |X1(i)|^2 + |X2(j)|^2 - (2 * X1(i)^T X2(j))
>     D = ((-2.0 * (X1 * X2.transpose())).colwise()
>         + X1.rowwise().squaredNorm()).rowwise()
>         + X2.rowwise().squaredNorm().transpose();
>     if (!squared) { D = (D.array().sqrt()).matrix(); }
> }
> 
> const TMatrix Matern52(const TMatrix& X1, const TMatrix& X2, TVector& length_scale) 
> {
>     TMatrix R(X1.rows(), X2.rows());
>     const TMatrix X1sc = X1.array().rowwise() / length_scale.transpose().array();
>     const TMatrix X2sc = X2.array().rowwise() / length_scale.transpose().array();
>     cdist(X1sc, X2sc, R, false);
>     R *= sqrt(5);
>     return ((1 + R.array() + square(R.array()) / 3) * (exp(-R.array()))).matrix();
> }
> 
> void xiong1d(const Eigen::Ref<const TMatrix>& X, Eigen::Ref<TMatrix> Y) 
> {
>     Y = -0.5 * (sin((40 * pow((X.array() - 0.85), 4)).array()) * cos((2.5 * (X.array() - 0.95)).array()) + 0.5 * (X.array() - 0.9) + 1);
> }
> 
> TMatrix sample_mvn(const TVector& mean, const TMatrix& K) 
> {
>     auto sampler = Eigen::Rand::makeMvNormalGen(mean, K);
>     return sampler.generate(gen_eigen);
> }
> 
> int main()
> {
>     std::cout << "SIMD arch: " << Eigen::SimdInstructionSetsInUse() << std::endl;
> 
>     TVector x_range = TVector::LinSpaced(10, 0, 1);
>     TMatrix X = Eigen::Map<TVector>(x_range.data(), 10);
>     TMatrix Y(X.rows(), 1);
>     xiong1d(X, Y);
>     TVector length_scale = TVector::Ones(1);
>     TMatrix K = Matern52(X, X, length_scale);
>     std::cout << "K =\n" << K << std::endl;
>     TVector mean = TVector::Zero(X.rows());
>     TMatrix mvn_samples = sample_mvn(mean, K);
>     std::cout << "MVN_SAMPLE =\n" << mvn_samples << std::endl;
>     return 0;
> }
> ```
> 
> It just replaces the random number generator with the c++ standard. I think the packet random number generator is suspicious. **If the above code works well, it becomes clear that the problem is with the packet random number generator.**


(For Comment Above) : [debug64_2.zip](https://github.com/bab2min/EigenRand/files/7229123/debug64_2.zip)

Actually, due to the use of other libraries I've added the following into my VS compiler command line (thats `Configuration Properties -> C/C++ -> Command Line`

```
/bigobj /permissive- /EHsc /D NOMINMAX 
```

So the compiler args are:
```
E:\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\CL.exe /c /I"E:\23620029-Faiz\C\SMh\include" /I"E:\23620029-Faiz\C\SMh\include\external\CppNumericalSolvers" /I"E:\23620029-Faiz\C\SMh\include\external\Eigen" /I"E:\23620029-Faiz\C\libs\EigenRand-0.3.6d" /I"E:\23620029-Faiz\C\SMh\include\external\EigenRand" /I"E:\23620029-Faiz\C\SMh\include\external\rapidcsv\src" /I"E:\23620029-Faiz\C\SMh\include\external\ThreadPool" /I"E:\23620029-Faiz\C\SMh\include\external\HighFive" /I"E:\23620029-Faiz\C\HDF5\include" /ZI /JMC /nologo /W3 /WX- /diagnostics:column /sdl /Od /D _DEBUG /D _CONSOLE /D _UNICODE /D UNICODE /D ADD_ /D HAVE_LAPACK_CONFIG_H /D LAPACK_COMPLEX_STRUCTURE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++17 /Fo"x64\Debug\\" /Fd"x64\Debug\vc142.pdb" /external:W3 /Gd /TP /FC /errorReport:prompt /bigobj /permissive- /EHsc /D NOMINMAX test_eigen_rand.cpp
```

**Comment by bab2min** [comment]
@izsahara 
Thanks for sharing the binary file.
I have confirmed that the same problem occurs in my environment.
Sorry for the inconvenience, but could you share the `tests.pdb` file that was created together when you built `tests.exe`?

**Comment by izsahara** [comment]
Sure, Not a problem (Note this is the test from the previous comment debug64_3.zip file)
[debug64_3_pdb.zip](https://github.com/bab2min/EigenRand/files/7231264/debug64_3_pdb.zip)


Thanks, let me know if any more is needed.

**Comment by bab2min** [comment]
Thank @izsahara. I finally figured out the cause.
There has been an internal change in the version of eigen you are using (https://gitlab.com/libeigen/eigen/-/tree/5f25bcf7d6918f5c6091fb4e961e5607e13b7324). This version is in transition from 3.3.9 to 3.4.0. So the external interface is similar to 3.3.9, but the internal implementation is similar to 3.4.0. Actually, this code says its version as `3.3.90` (https://gitlab.com/libeigen/eigen/-/blob/5f25bcf7d6918f5c6091fb4e961e5607e13b7324/Eigen/src/Core/util/Macros.h#L20)

Especially, in SSE packet math of Eigen 3.3.90, `pandnot` is implemented like: https://gitlab.com/libeigen/eigen/-/blob/5f25bcf7d6918f5c6091fb4e961e5607e13b7324/Eigen/src/Core/arch/SSE/PacketMath.h#L480

But in the one of official Eigen 3.3.9, `pandnot` is implemented like:
https://gitlab.com/libeigen/eigen/-/blob/3.3/Eigen/src/Core/arch/SSE/PacketMath.h#L303

This difference resulted in a huge difference in the `sincos` function in EigenRand, and ultimately produced a wrong normal distribution.
(And, Issue #29 seems to be occurring for the same reason.)

Currently, I am working on a patch to make EigenRand compatible with version 3.4.0 as well. When this is done, it seems that the problem that occurs in version 3.3.90 will also be resolved. Until then, I recommend that you use the official release version of Eigen 3.3.9.
