### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by nim65s** [bab2min/EigenRand#56]
Hello,

Multiple nice things were added since [v0.5.0](https://github.com/bab2min/EigenRand/releases/tag/v0.5.0), and it seems that there is currently a pause in the commits to the main branch, so it is probably the perfect time for a new release.

Could you make one ?

**Comment by bab2min** [comment]
Hi @nim65s 
Sure! I've just make a new release v0.5.1.
Thank you for your warm interest!

**Comment by nim65s** [comment]
Perfect, thanks !

**Comment by GaetanLepage** [comment]
Wow that was fast... Unlike https://github.com/triton-lang/triton/issues/3535...
